export const dummyData = [
  {
    awbNumber: "AWB001",
    awbOrigin: "JFK",
    awbDest: "LAX",
    pcs: 10,
    wt: 500,
    vol: 1.5,
    uom: "kg",
    fltDate: "2024-06-01",
    fltOrigin: "JFK",
    fltDestination: "LAX",
    action: "Shipped",
    message: "Shipment on time",
    updatedBy: "admin",
    updatedOn: "2024-06-01",
  },
  {
    awbNumber: "AWB002",
    awbOrigin: "SFO",
    awbDest: "ORD",
    pcs: 20,
    wt: 1000,
    vol: 3.0,
    uom: "kg",
    fltDate: "2024-06-02",
    fltOrigin: "SFO",
    fltDestination: "ORD",
    action: "Delayed",
    message: "Flight delayed due to weather",
    updatedBy: "system",
    updatedOn: "2024-06-02",
  },
  {
    awbNumber: "AWB003",
    awbOrigin: "LAX",
    awbDest: "MIA",
    pcs: 5,
    wt: 250,
    vol: 0.75,
    uom: "kg",
    fltDate: "2024-06-03",
    fltOrigin: "LAX",
    fltDestination: "MIA",
    action: "Shipped",
    message: "Shipment on time",
    updatedBy: "user",
    updatedOn: "2024-06-03",
  },
  {
    awbNumber: "AWB004",
    awbOrigin: "MIA",
    awbDest: "DFW",
    pcs: 15,
    wt: 750,
    vol: 2.25,
    uom: "kg",
    fltDate: "2024-06-04",
    fltOrigin: "MIA",
    fltDestination: "DFW",
    action: "Cancelled",
    message: "Flight cancelled",
    updatedBy: "admin",
    updatedOn: "2024-06-04",
  },
  {
    awbNumber: "AWB005",
    awbOrigin: "DFW",
    awbDest: "JFK",
    pcs: 25,
    wt: 1250,
    vol: 3.75,
    uom: "kg",
    fltDate: "2024-06-05",
    fltOrigin: "DFW",
    fltDestination: "JFK",
    action: "Shipped",
    message: "Shipment on time",
    updatedBy: "system",
    updatedOn: "2024-06-05",
  },
]
