export const masterList = [
  {
    key: "atfPrice",
    value: "ATF Price",
  },
  {
    key: "exchangeRate",
    value: "Exchange Rate",
  },
  {
    key: "oc",
    value: "OC",
  },
  {
    key: "ocdc",
    value: "OCDC",
  },
  {
    key: "prorate",
    value: "Prorate",
  },
  {
    key: "spotRate",
    value: "Cart",
  },
  {
    key: "sac",
    value: "SAC",
  },
  {
    key: "rateline",
    value: "Rateline",
  },
]

export const dummyData = [
  {
    userCode: "USR001",
    accessorKey: "updatedBy",
    fieldName: "email",
    updatedBy: "admin",
    newValue: "newuser@example.com",
    description: "Updated the user's email address",
    masterKey: "atfPrice",
    updatedAt: "2024-05-01T10:15:30Z",
  },
  {
    userCode: "USR002",
    accessorKey: "updatedBy",
    fieldName: "phoneNumber",
    updatedBy: "user",
    newValue: "+1234567890",
    description: "User updated their phone number",
    masterKey: "oc",
    updatedAt: "2024-05-02T11:20:45Z",
  },
  {
    userCode: "USR003",
    accessorKey: "updatedBy",
    fieldName: "address",
    updatedBy: "admin",
    newValue: "123 New Street, Cityville",
    description: "Admin updated the user's address",
    masterKey: "exchangeRate",
    updatedAt: "2024-05-03T12:25:50Z",
  },
  {
    userCode: "USR004",
    accessorKey: "updatedBy",
    fieldName: "username",
    updatedBy: "user",
    newValue: "newusername",
    description: "User updated their username",
    masterKey: "atfPrice",
    updatedAt: "2024-05-04T13:30:55Z",
  },
  {
    userCode: "USR005",
    accessorKey: "updatedBy",
    fieldName: "password",
    updatedBy: "system",
    newValue: "********",
    description: "System reset the user's password",
    masterKey: "oc",
    updatedAt: "2024-05-05T14:35:00Z",
  },
  {
    userCode: "USR006",
    accessorKey: "updatedBy",
    fieldName: "profilePicture",
    updatedBy: "user",
    newValue: "profile_pic_123.jpg",
    description: "User updated their profile picture",
    masterKey: "oc",
    updatedAt: "2024-05-06T15:40:05Z",
  },
  {
    userCode: "USR007",
    accessorKey: "updatedBy",
    fieldName: "email",
    updatedBy: "admin",
    newValue: "anotheruser@example.com",
    description: "Admin updated the user's email address",
    masterKey: "atfPrice",
    updatedAt: "2024-05-07T16:45:10Z",
  },
  {
    userCode: "USR008",
    accessorKey: "updatedBy",
    fieldName: "subscriptionPlan",
    updatedBy: "user",
    newValue: "Premium",
    description: "User upgraded their subscription plan",
    masterKey: "oc",
    updatedAt: "2024-05-08T17:50:15Z",
  },
  {
    userCode: "USR009",
    accessorKey: "updatedBy",
    fieldName: "languagePreference",
    updatedBy: "user",
    newValue: "Spanish",
    description: "User updated their language preference",
    masterKey: "oc",
    updatedAt: "2024-05-09T18:55:20Z",
  },
  {
    userCode: "USR010",
    accessorKey: "updatedBy",
    fieldName: "dateOfBirth",
    updatedBy: "user",
    newValue: "1990-01-01",
    description: "User updated their date of birth",
    masterKey: "oc",
    updatedAt: "2024-05-10T19:00:25Z",
  },
]
