"use client"

import { ColumnDef } from "@tanstack/react-table";
import { Checkbox } from "@/components/ui/checkbox"


export const columns: ColumnDef<any>[] = [
    {
        id: "select",
        header: ({ table }) => (
            <Checkbox
                checked={table.getIsAllPageRowsSelected()}
                onCheckedChange={(value) => table.toggleAllPageRowsSelected(!!value)}
                aria-label="Select all"
            />
        ),
        cell: ({ row }) => (
            <Checkbox
                checked={row.getIsSelected()}
                onCheckedChange={(value) => row.toggleSelected(!!value)}
                aria-label="Select row"
            />
        ),
        enableSorting: false,
        enableHiding: false,
    },
    {
        accessorKey: "reportId",
        header: "Report ID"
    },
    {
        accessorKey: "reportName",
        header: "Report Name"
    },
    {
        accessorKey: "generatedBy",
        header: "Generated By"
    },
    {
        accessorKey: "generatedOn",
        header: "Generated On"
    },
    {
        accessorKey: "status",
        header: "Status"
    },
    {
        accessorKey: "downloadLink",
        header: "Download Link",
        cell: ({ row }) => (
            row.original.downloadLink ? (
                <a href={row.original.downloadLink} target="_blank" rel="noopener noreferrer">Download</a>
            ) : "N/A"
        )
    },
    {
        accessorKey: "remarks",
        header: "Remarks"
    }
];
    




