export const dummyData = [
  {
    reportId: "RPT001",
    reportName: "Monthly Sales",
    generatedBy: "John Doe",
    generatedOn: "2024-01-01",
    status: "Completed",
    downloadLink: "http://example.com/download/RPT001",
    remarks: "Generated successfully.",
  },
  {
    reportId: "RPT002",
    reportName: "Inventory Summary",
    generatedBy: "Jane Smith",
    generatedOn: "2024-01-05",
    status: "Completed",
    downloadLink: "http://example.com/download/RPT002",
    remarks: "Generated successfully.",
  },
  {
    reportId: "RPT003",
    reportName: "Customer Feedback",
    generatedBy: "Mike Johnson",
    generatedOn: "2024-01-10",
    status: "Failed",
    downloadLink: "",
    remarks: "Error in data extraction.",
  },
  {
    reportId: "RPT004",
    reportName: "Quarterly Financials",
    generatedBy: "Emily Davis",
    generatedOn: "2024-01-15",
    status: "In Progress",
    downloadLink: "",
    remarks: "Generation in progress.",
  },
  {
    reportId: "RPT005",
    reportName: "Yearly Overview",
    generatedBy: "Chris Lee",
    generatedOn: "2024-01-20",
    status: "Completed",
    downloadLink: "http://example.com/download/RPT005",
    remarks: "Generated successfully.",
  },
]
