export const typelist = [
  {
    key: "actual",
    value: "Actual",
  },
  {
    key: "backup",
    value: "Backup",
  },
]

export const dummyData = [
  {
    serialNumber: 1,
    filename: "file1.csv",
    type: "CSV",
    uploadedBy: "admin",
    station: "JFK",
    recordCount: 100,
    successCount: 90,
    failureCount: 10,
    updatedAt: "2024-05-01T10:00:00Z",
    action: "Processed",
  },
  {
    serialNumber: 2,
    filename: "file2.csv",
    type: "CSV",
    uploadedBy: "user1",
    station: "LAX",
    recordCount: 200,
    successCount: 180,
    failureCount: 20,
    updatedAt: "2024-05-02T11:00:00Z",
    action: "Processed",
  },
  {
    serialNumber: 3,
    filename: "file3.csv",
    type: "CSV",
    uploadedBy: "user2",
    station: "ORD",
    recordCount: 150,
    successCount: 140,
    failureCount: 10,
    updatedAt: "2024-05-03T12:00:00Z",
    action: "Processed",
  },
  {
    serialNumber: 4,
    filename: "file4.csv",
    type: "CSV",
    uploadedBy: "admin",
    station: "ATL",
    recordCount: 250,
    successCount: 240,
    failureCount: 10,
    updatedAt: "2024-05-04T13:00:00Z",
    action: "Processed",
  },
  {
    serialNumber: 5,
    filename: "file5.csv",
    type: "CSV",
    uploadedBy: "user3",
    station: "SFO",
    recordCount: 300,
    successCount: 290,
    failureCount: 10,
    updatedAt: "2024-05-05T14:00:00Z",
    action: "Processed",
  },
]
