import {
  AwbType,
  UldType,
} from "@/components/operation/ArrivalManifest/ArrivalManifest/columns"

export const DUMMY_DATA_AWB: AwbType[] = [
  {
    awb_number: "123-45678901",
    origin: "JFK",
    dest: "LAX",
    mft_pcs: "10",
    mft_wt: "500",
    arr_pcs: "10",
    arr_wt: "500",
    rem_pcs: "0",
    rem_wt: "0",
    priority: "High",
    discrepancy: "None",
    comm_code: "ELEC",
    shipper: "ABC Corp",
    consignee: "XYZ Inc",
    remarks: "Handle with care",
    handling_instruction: "Fragile",
    flt: "FL123",
    flt_date: "2024-06-01",
    arrival_time: "10:00",
    next_flt: "FL124",
    pol: "JFK",
    uom: "kg",
    acc_pcs: "10",
    acc_wt: "500",
    security_check: "Passed",
  },
  {
    awb_number: "123-45678902",
    origin: "ORD",
    dest: "MIA",
    mft_pcs: "8",
    mft_wt: "320",
    arr_pcs: "8",
    arr_wt: "320",
    rem_pcs: "0",
    rem_wt: "0",
    priority: "Medium",
    discrepancy: "None",
    comm_code: "MAC",
    shipper: "DEF Ltd",
    consignee: "UVW LLC",
    remarks: "Fragile items",
    handling_instruction: "Handle with care",
    flt: "FL125",
    flt_date: "2024-06-02",
    arrival_time: "12:00",
    next_flt: "FL126",
    pol: "ORD",
    uom: "kg",
    acc_pcs: "8",
    acc_wt: "320",
    security_check: "Passed",
  },
  {
    awb_number: "123-45678903",
    origin: "ATL",
    dest: "SEA",
    mft_pcs: "15",
    mft_wt: "750",
    arr_pcs: "15",
    arr_wt: "750",
    rem_pcs: "0",
    rem_wt: "0",
    priority: "Low",
    discrepancy: "None",
    comm_code: "TXT",
    shipper: "GHI Co",
    consignee: "RST Corp",
    remarks: "Keep dry",
    handling_instruction: "Do not wet",
    flt: "FL127",
    flt_date: "2024-06-03",
    arrival_time: "14:00",
    next_flt: "FL128",
    pol: "ATL",
    uom: "kg",
    acc_pcs: "15",
    acc_wt: "750",
    security_check: "Passed",
  },
  {
    awb_number: "123-45678904",
    origin: "DFW",
    dest: "SFO",
    mft_pcs: "12",
    mft_wt: "600",
    arr_pcs: "12",
    arr_wt: "600",
    rem_pcs: "0",
    rem_wt: "0",
    priority: "High",
    discrepancy: "None",
    comm_code: "PER",
    shipper: "JKL Inc",
    consignee: "OPQ Ltd",
    remarks: "Refrigerated",
    handling_instruction: "Keep cold",
    flt: "FL129",
    flt_date: "2024-06-04",
    arrival_time: "16:00",
    next_flt: "FL130",
    pol: "DFW",
    uom: "kg",
    acc_pcs: "12",
    acc_wt: "600",
    security_check: "Passed",
  },
  {
    awb_number: "123-45678905",
    origin: "LAX",
    dest: "ORD",
    mft_pcs: "20",
    mft_wt: "1000",
    arr_pcs: "20",
    arr_wt: "1000",
    rem_pcs: "0",
    rem_wt: "0",
    priority: "Medium",
    discrepancy: "None",
    comm_code: "GEN",
    shipper: "MNO Ltd",
    consignee: "VWX Corp",
    remarks: "Handle with care",
    handling_instruction: "Fragile",
    flt: "FL131",
    flt_date: "2024-06-05",
    arrival_time: "18:00",
    next_flt: "FL132",
    pol: "LAX",
    uom: "kg",
    acc_pcs: "20",
    acc_wt: "1000",
    security_check: "Passed",
  },
]

export const DUMMY_DATA_ULD: UldType[] = [
  {
    uld: "ULD001",
    origin: "JFK",
    dest: "LAX",
    uld_wt: "1000",
    scale_wt: "1050",
    awb_ct: "5",
    awb_pcs: "50",
    awb_wt: "500",
    priority: "High",
    arrived: "Yes",
    flt: "FL123",
    flt_date: "2024-06-01",
    pol: "JFK",
    uom: "kg",
    handling_instruction: "Fragile",
    remark: "Handle with care",
  },
  {
    uld: "ULD002",
    origin: "ORD",
    dest: "MIA",
    uld_wt: "1200",
    scale_wt: "1250",
    awb_ct: "4",
    awb_pcs: "40",
    awb_wt: "400",
    priority: "Medium",
    arrived: "No",
    flt: "FL124",
    flt_date: "2024-06-02",
    pol: "ORD",
    uom: "kg",
    handling_instruction: "Handle with care",
    remark: "Fragile items",
  },
  {
    uld: "ULD003",
    origin: "ATL",
    dest: "SEA",
    uld_wt: "1500",
    scale_wt: "1550",
    awb_ct: "6",
    awb_pcs: "60",
    awb_wt: "600",
    priority: "Low",
    arrived: "Yes",
    flt: "FL125",
    flt_date: "2024-06-03",
    pol: "ATL",
    uom: "kg",
    handling_instruction: "Do not wet",
    remark: "Keep dry",
  },
  {
    uld: "ULD004",
    origin: "DFW",
    dest: "SFO",
    uld_wt: "1800",
    scale_wt: "1850",
    awb_ct: "7",
    awb_pcs: "70",
    awb_wt: "700",
    priority: "High",
    arrived: "No",
    flt: "FL126",
    flt_date: "2024-06-04",
    pol: "DFW",
    uom: "kg",
    handling_instruction: "Fragile",
    remark: "Handle with care",
  },
  {
    uld: "ULD005",
    origin: "LAX",
    dest: "ORD",
    uld_wt: "2000",
    scale_wt: "2050",
    awb_ct: "8",
    awb_pcs: "80",
    awb_wt: "800",
    priority: "Medium",
    arrived: "Yes",
    flt: "FL127",
    flt_date: "2024-06-05",
    pol: "LAX",
    uom: "kg",
    handling_instruction: "Keep cold",
    remark: "Refrigerated",
  },
  {
    uld: "ULD006",
    origin: "JFK",
    dest: "MIA",
    uld_wt: "2200",
    scale_wt: "2250",
    awb_ct: "9",
    awb_pcs: "90",
    awb_wt: "900",
    priority: "Low",
    arrived: "No",
    flt: "FL128",
    flt_date: "2024-06-06",
    pol: "JFK",
    uom: "kg",
    handling_instruction: "Handle with care",
    remark: "Fragile items",
  },
  {
    uld: "ULD007",
    origin: "ORD",
    dest: "SEA",
    uld_wt: "2400",
    scale_wt: "2450",
    awb_ct: "10",
    awb_pcs: "100",
    awb_wt: "1000",
    priority: "High",
    arrived: "Yes",
    flt: "FL129",
    flt_date: "2024-06-07",
    pol: "ORD",
    uom: "kg",
    handling_instruction: "Keep dry",
    remark: "Do not wet",
  },
  {
    uld: "ULD008",
    origin: "ATL",
    dest: "SFO",
    uld_wt: "2600",
    scale_wt: "2650",
    awb_ct: "11",
    awb_pcs: "110",
    awb_wt: "1100",
    priority: "Medium",
    arrived: "No",
    flt: "FL130",
    flt_date: "2024-06-08",
    pol: "ATL",
    uom: "kg",
    handling_instruction: "Handle with care",
    remark: "Fragile items",
  },
]

export async function getData(param = "awb") {
  switch (param) {
    case "uld":
      return DUMMY_DATA_ULD
    default:
      return DUMMY_DATA_AWB
  }
}
