import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
    lang="en"
    className={cn(
      "antialiased scrollbar scroll-smooth",

      ` ${GeistSans.variable} ${GeistMono.variable}`
    )}

  >
    <body
      className="text-black dark:text-white from-snow via-floralWhite to-lavender
     bg-gradient-to-br bg-black"

    >
      {/* <ProgressBar />
      <Nav /> */}
      {children}
    </body>
  </html>
  );
}
