import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";
import { CollaborativeApp } from "@/app/CollaborativeApp";
import { Room } from "@/app/Room";
import { cn } from "@/lib/utils";
import { GoogleTagManager } from "@next/third-parties/google";
import UIWrapper from "@/components/ui/wrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isProduction = process.env.NODE_ENV === "production";
  const gtmId = process.env.NEXT_PUBLIC_GTM_ID;
  return (
    <html
      lang="en"
      className={cn(
        "scrollbar h-full scroll-smooth antialiased dark",

        ` ${GeistSans.className}`
      )}
    >
      {isProduction && gtmId && <GoogleTagManager gtmId={gtmId} />}
      <body className="  h-full bg-zinc-900 text-white custom-scrollbar">
        {/* <ProgressBar />
      <Nav /> */}
        <UIWrapper>{children}</UIWrapper>
      </body>
    </html>
  );
}
