import type { List } from "@/components/operation/StockAllocation/columns";

export const STOCK_LIST_DATA: List[] = [
  {
    level: "HO",
    awb_prefix: "001",
    from: "Station A",
    to: "Station B",
    status: "Active",
    allocation_time: "2024-05-23 08:00",
    allocated_by: "User A",
    available_awb: "50",
    last_allocated: "2024-05-23 10:00",
    cnote_type: "AWB",
    stock_type: "Domestic",
    awb_type: "All",
    allocated: "30",
    job_status: "Success",
    duration: "2 hours"
  },
  {
    level: "Agent",
    awb_prefix: "002",
    from: "Station B",
    to: "Station C",
    status: "Pending",
    allocation_time: "2024-05-24 09:00",
    allocated_by: "User B",
    available_awb: "40",
    last_allocated: "2024-05-24 11:00",
    cnote_type: "AXB",
    stock_type: "International",
    awb_type: "Physical",
    allocated: "20",
    job_status: "Pending",
    duration: "3 hours"
  },
  {
    level: "Subagent",
    awb_prefix: "003",
    from: "Station C",
    to: "Station D",
    status: "Inactive",
    allocation_time: "2024-05-25 10:00",
    allocated_by: "User C",
    available_awb: "60",
    last_allocated: "2024-05-25 12:00",
    cnote_type: "MWB",
    stock_type: "Domestic",
    awb_type: "Electronic",
    allocated: "35",
    job_status: "Failed",
    duration: "4 hours"
  },
  {
    level: "HO",
    awb_prefix: "004",
    from: "Station D",
    to: "Station E",
    status: "Active",
    allocation_time: "2024-05-26 11:00",
    allocated_by: "User D",
    available_awb: "70",
    last_allocated: "2024-05-26 13:00",
    cnote_type: "AWB",
    stock_type: "International",
    awb_type: "Neutral",
    allocated: "45",
    job_status: "Success",
    duration: "1 hour"
  },
  {
    level: "Agent",
    awb_prefix: "005",
    from: "Station E",
    to: "Station F",
    status: "Pending",
    allocation_time: "2024-05-27 12:00",
    allocated_by: "User E",
    available_awb: "80",
    last_allocated: "2024-05-27 14:00",
    cnote_type: "AXB",
    stock_type: "Domestic",
    awb_type: "All",
    allocated: "50",
    job_status: "Pending",
    duration: "5 hours"
  },
  {
    level: "Subagent",
    awb_prefix: "006",
    from: "Station F",
    to: "Station G",
    status: "Inactive",
    allocation_time: "2024-05-28 13:00",
    allocated_by: "User F",
    available_awb: "90",
    last_allocated: "2024-05-28 15:00",
    cnote_type: "MWB",
    stock_type: "International",
    awb_type: "Physical",
    allocated: "25",
    job_status: "Failed",
    duration: "6 hours"
  },
  {
    level: "HO",
    awb_prefix: "007",
    from: "Station G",
    to: "Station H",
    status: "Active",
    allocation_time: "2024-05-29 14:00",
    allocated_by: "User G",
    available_awb: "100",
    last_allocated: "2024-05-29 16:00",
    cnote_type: "AWB",
    stock_type: "Domestic",
    awb_type: "Electronic",
    allocated: "55",
    job_status: "Success",
    duration: "7 hours"
  },
  {
    level: "Agent",
    awb_prefix: "008",
    from: "Station H",
    to: "Station I",
    status: "Pending",
    allocation_time: "2024-05-30 15:00",
    allocated_by: "User H",
    available_awb: "110",
    last_allocated: "2024-05-30 17:00",
    cnote_type: "AXB",
    stock_type: "International",
    awb_type: "Neutral",
    allocated: "60",
    job_status: "Pending",
    duration: "8 hours"
  },
  {
    level: "Subagent",
    awb_prefix: "009",
    from: "Station I",
    to: "Station J",
    status: "Inactive",
    allocation_time: "2024-05-31 16:00",
    allocated_by: "User I",
    available_awb: "120",
    last_allocated: "2024-05-31 18:00",
    cnote_type: "MWB",
    stock_type: "Domestic",
    awb_type: "All",
    allocated: "65",
    job_status: "Failed",
    duration: "9 hours"
  },
  {
    level: "HO",
    awb_prefix: "010",
    from: "Station J",
    to: "Station K",
    status: "Active",
    allocation_time: "2024-06-01 17:00",
    allocated_by: "User J",
    available_awb: "130",
    last_allocated: "2024-06-01 19:00",
    cnote_type: "AWB",
    stock_type: "International",
    awb_type: "Physical",
    allocated: "70",
    job_status: "Success",
    duration: "10 hours"
  }
];

export async function getData(param = 'stock-list') {
  switch (param) {
    case 'stock-allocation':
      return STOCK_LIST_DATA;
    default:
      return STOCK_LIST_DATA;
  }
}
