import { AircraftFormValues } from "@/schemas/aircraft/aircraft"

export const formDefaultValues: AircraftFormValues = {
  aft_h: "",
  aft_w: "",
  aircraft_tail_numbers: [
    {
      id: "",
      status_id: "",
      tail_number: "",
    },
  ],
  aircraft_type: "",
  body_type_id: "",
  bulk: "",
  bulk_cubic_id: "",
  bulk_h: "",
  bulk_unit_id: "",
  bulk_w: "",
  cargo_capacity: "",
  cargo_capacity_unit_id: "",
  fwd: "",
  fwd_h: "",
  fwd_w: "",
  count: "",
  fwt: "",
  gl_code_id: "",
  landing_weight: "",
  landing_weight_unit_id: "",
  max_bulk_capacity_volume: "",
  max_bulk_capacity_volume_unit_id: "",
  max_bulk_capacity_weight: "",
  max_bulk_capacity_weight_unit_id: "",
  max_dimension_breadth: "",
  max_dimension_height: "",
  manufacturer: "",
  max_dimension_length: "",
  max_dimension_unit_id: "",
  max_volume: "",
  max_volume_unit_id: "",
  max_zero_fuel_weight: "",
  max_zero_fuel_weight_unit_id: "",
  mtow: "",
  mtow_unit_id: "",
  passenger_capacity: "",
  restricted_weight_piece: "",
  restricted_weight_piece_unit_id: "",
  status_id: "",
  uld_position: "",
  version: "",
}
