import { AircraftFormValues } from "@/schemas/aircraft/aircraft"
import { nanoid } from "nanoid"

type AircraftManufacturer = "Boeing" | "Airbus"

type AircraftTypeListOfType =
  | "A220"
  | "A320"
  | "A330"
  | "A340"
  | "A350"
  | "A380"
  | "737"
  | "747"
  | "757"
  | "767"
  | "777"
  | "787"

type AircraftType = {
  manufacturer: AircraftManufacturer
  types: {
    type: string
    versions: { version: string; details: Partial<AircraftFormValues> }[]
  }[]
}[]

const DEFAULT_BODY_TYPE_ID = "1161055d-0f85-48f4-844e-0c29add31ba8"
const DEFAULT_BODY_TYPE_ID_WIDE = "ac201762-5b55-44ab-85c9-0e8f956b8e00"
const DEFAULT_WEIGHT_UNIT_ID = "a708c7ab-c41a-45c3-a3f2-9ae6cb21f47c"
const DEFAULT_VOLUME_UNIT_ID = "aefd86d6-6fe7-4fcf-8a42-5ef860542401"
const DEFAULT_DIMENSION_UNIT_ID = "767c9495-c8f8-48fe-82cb-28d7a42a016d"

const DEFAULT_TAIL_STATUS_ID_ACTIVE = "a2a781e6-c892-46e4-ab3e-fb344727cfd8" // Assuming this is the ID for "Active"
const DEFAULT_GL_CODE_WIDE = "ac201762-5b55-44ab-85c9-0e8f956b8e00"
const DEFAULT_AIRCRAFT_STATUS_ID_ACTIVE = "a2a781e6-c892-46e4-ab3e-fb344727cfd8"

// Example Test Dummy Data default values
export const aircraftTypes: AircraftType = [
  {
    manufacturer: "Airbus",
    types: [
      {
        type: "A330", //
        versions: [
          {
            version: "200", //
            details: {
              mtow: "242000", // Max takeoff weight
              mtow_unit_id: DEFAULT_WEIGHT_UNIT_ID,
              max_zero_fuel_weight: "175000", //
              max_zero_fuel_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
              body_type_id: DEFAULT_BODY_TYPE_ID,
              passenger_capacity: "239", //
              uld_position: "26",
              landing_weight: "187000",
              landing_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
              cargo_capacity: "33300",
              cargo_capacity_unit_id: DEFAULT_VOLUME_UNIT_ID,
              max_bulk_capacity_weight: "13500",
              max_bulk_capacity_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
              max_bulk_capacity_volume: "14.8",
              max_bulk_capacity_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
              max_volume: "168",
              max_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
              restricted_weight_piece: "200",
              restricted_weight_piece_unit_id: DEFAULT_WEIGHT_UNIT_ID,
              max_dimension_length: "3",
              max_dimension_breadth: "2.4",
              max_dimension_height: "1.7",
              max_dimension_unit_id: DEFAULT_DIMENSION_UNIT_ID,
              aft_h: "1.65",
              aft_w: "3.58",
              fwd_h: "1.65",
              fwd_w: "3.58",
              bulk_h: "1.12",
              bulk_w: "1.35",
              bulk_unit_id: DEFAULT_DIMENSION_UNIT_ID,
              fwt: "15",
              fwd: "20",
              bulk: "30",
              bulk_cubic_id: DEFAULT_VOLUME_UNIT_ID,
              gl_code_id: DEFAULT_GL_CODE_WIDE,
              status_id: DEFAULT_AIRCRAFT_STATUS_ID_ACTIVE,
              aircraft_tail_numbers: [
                {
                  tail_number: "KOM",
                  status_id: DEFAULT_TAIL_STATUS_ID_ACTIVE,
                },
                {
                  tail_number: "NUL",
                  status_id: DEFAULT_TAIL_STATUS_ID_ACTIVE,
                },
                {
                  tail_number: "JQG",
                  status_id: DEFAULT_TAIL_STATUS_ID_ACTIVE,
                },
                {
                  tail_number: "OAQ",
                  status_id: DEFAULT_TAIL_STATUS_ID_ACTIVE,
                },
                {
                  tail_number: "OAP",
                  status_id: DEFAULT_TAIL_STATUS_ID_ACTIVE,
                },
              ],
            },
          },
        ],
      },
      {
        type: "A340", //
        versions: [
          {
            version: "300", //
            details: {
              mtow: "276500", // Max takeoff weight
              mtow_unit_id: DEFAULT_WEIGHT_UNIT_ID,
              max_zero_fuel_weight: "183000", //
              max_zero_fuel_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
              body_type_id: DEFAULT_BODY_TYPE_ID_WIDE,
              passenger_capacity: "250", //
              uld_position: "33",
              landing_weight: "192000",
              landing_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
              cargo_capacity: "35000",
              cargo_capacity_unit_id: DEFAULT_VOLUME_UNIT_ID,
              max_bulk_capacity_weight: "13600",
              max_bulk_capacity_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
              max_bulk_capacity_volume: "19.7",
              max_bulk_capacity_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
              max_volume: "175",
              max_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
              restricted_weight_piece: "200",
              restricted_weight_piece_unit_id: DEFAULT_WEIGHT_UNIT_ID,
              max_dimension_length: "3.1",
              max_dimension_breadth: "2.5",
              max_dimension_height: "1.7",
              max_dimension_unit_id: DEFAULT_DIMENSION_UNIT_ID,
              aft_h: "1.7",
              aft_w: "3.6",
              fwd_h: "1.7",
              fwd_w: "3.6",
              bulk_h: "1.15",
              bulk_w: "1.4",
              bulk_unit_id: DEFAULT_DIMENSION_UNIT_ID,
              fwt: "18",
              fwd: "22",
              bulk: "32",
              bulk_cubic_id: DEFAULT_VOLUME_UNIT_ID,
              gl_code_id: DEFAULT_GL_CODE_WIDE,
              status_id: DEFAULT_AIRCRAFT_STATUS_ID_ACTIVE,
              aircraft_tail_numbers: [
                {
                  tail_number: "MQM",
                  status_id: DEFAULT_TAIL_STATUS_ID_ACTIVE,
                },
              ],
            },
          },
        ],
      },
    ],
  },
]

// export const aircraftTypes_old_data: AircraftType = [
//   {
//     manufacturer: "Boeing",
//     types: [
//       {
//         type: "737",
//         versions: [
//           {
//             version: "700",
//             details: {
//               mtow: "70000",
//               mtow_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_zero_fuel_weight: "58000",
//               max_zero_fuel_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               body_type_id: DEFAULT_BODY_TYPE_ID,
//               passenger_capacity: "140",
//               uld_position: "6",
//               landing_weight: "62000",
//               landing_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               cargo_capacity: "30000",
//               cargo_capacity_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               max_bulk_capacity_weight: "15000",
//               max_bulk_capacity_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_bulk_capacity_volume: "200",
//               max_bulk_capacity_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               max_volume: "300",
//               max_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               restricted_weight_piece: "200",
//               restricted_weight_piece_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_dimension_length: "2",
//               max_dimension_breadth: "1.5",
//               max_dimension_height: "1.5",
//               max_dimension_unit_id: DEFAULT_DIMENSION_UNIT_ID,
//               aft_h: "5",
//               aft_w: "4",
//               fwd_h: "5",
//               fwd_w: "4",
//               bulk_h: "4",
//               bulk_w: "3",
//               bulk_unit_id: DEFAULT_DIMENSION_UNIT_ID,
//               fwt: "15",
//               fwd: "20",
//               bulk: "30",
//               bulk_cubic_id: DEFAULT_VOLUME_UNIT_ID,
//             },
//           },
//           {
//             version: "800",
//             details: {
//               mtow: "80000",
//               mtow_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_zero_fuel_weight: "58000",
//               max_zero_fuel_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               body_type_id: DEFAULT_BODY_TYPE_ID,
//               passenger_capacity: "140",
//               uld_position: "6",
//               landing_weight: "62000",
//               landing_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               cargo_capacity: "30000",
//               cargo_capacity_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               max_bulk_capacity_weight: "15000",
//               max_bulk_capacity_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_bulk_capacity_volume: "200",
//               max_bulk_capacity_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               max_volume: "300",
//               max_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               restricted_weight_piece: "200",
//               restricted_weight_piece_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_dimension_length: "2",
//               max_dimension_breadth: "1.5",
//               max_dimension_height: "1.5",
//               max_dimension_unit_id: DEFAULT_DIMENSION_UNIT_ID,
//               aft_h: "5",
//               aft_w: "4",
//               fwd_h: "5",
//               fwd_w: "4",
//               bulk_h: "4",
//               bulk_w: "3",
//               bulk_unit_id: DEFAULT_DIMENSION_UNIT_ID,
//               fwt: "15",
//               fwd: "20",
//               bulk: "30",
//               bulk_cubic_id: DEFAULT_VOLUME_UNIT_ID,
//             },
//           },
//           {
//             version: "900",
//             details: {
//               mtow: "80000",
//               mtow_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_zero_fuel_weight: "58000",
//               max_zero_fuel_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               body_type_id: DEFAULT_BODY_TYPE_ID,
//               passenger_capacity: "140",
//               uld_position: "6",
//               landing_weight: "62000",
//               landing_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               cargo_capacity: "30000",
//               cargo_capacity_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               max_bulk_capacity_weight: "15000",
//               max_bulk_capacity_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_bulk_capacity_volume: "200",
//               max_bulk_capacity_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               max_volume: "300",
//               max_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               restricted_weight_piece: "200",
//               restricted_weight_piece_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_dimension_length: "2",
//               max_dimension_breadth: "1.5",
//               max_dimension_height: "1.5",
//               max_dimension_unit_id: DEFAULT_DIMENSION_UNIT_ID,
//               aft_h: "5",
//               aft_w: "4",
//               fwd_h: "5",
//               fwd_w: "4",
//               bulk_h: "4",
//               bulk_w: "3",
//               bulk_unit_id: DEFAULT_DIMENSION_UNIT_ID,
//               fwt: "15",
//               fwd: "20",
//               bulk: "30",
//               bulk_cubic_id: DEFAULT_VOLUME_UNIT_ID,
//             },
//           },
//           {
//             version: "MAX 8",
//             details: {
//               mtow: "80000",
//               mtow_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_zero_fuel_weight: "58000",
//               max_zero_fuel_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               body_type_id: DEFAULT_BODY_TYPE_ID,
//               passenger_capacity: "140",
//               uld_position: "6",
//               landing_weight: "62000",
//               landing_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               cargo_capacity: "30000",
//               cargo_capacity_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               max_bulk_capacity_weight: "15000",
//               max_bulk_capacity_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_bulk_capacity_volume: "200",
//               max_bulk_capacity_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               max_volume: "300",
//               max_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               restricted_weight_piece: "200",
//               restricted_weight_piece_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_dimension_length: "2",
//               max_dimension_breadth: "1.5",
//               max_dimension_height: "1.5",
//               max_dimension_unit_id: DEFAULT_DIMENSION_UNIT_ID,
//               aft_h: "5",
//               aft_w: "4",
//               fwd_h: "5",
//               fwd_w: "4",
//               bulk_h: "4",
//               bulk_w: "3",
//               bulk_unit_id: DEFAULT_DIMENSION_UNIT_ID,
//               fwt: "15",
//               fwd: "20",
//               bulk: "30",
//               bulk_cubic_id: DEFAULT_VOLUME_UNIT_ID,
//             },
//           },
//           {
//             version: "MAX 9",
//             details: {
//               mtow: "80000",
//               mtow_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_zero_fuel_weight: "58000",
//               max_zero_fuel_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               body_type_id: DEFAULT_BODY_TYPE_ID,
//               passenger_capacity: "140",
//               uld_position: "6",
//               landing_weight: "62000",
//               landing_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               cargo_capacity: "30000",
//               cargo_capacity_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               max_bulk_capacity_weight: "15000",
//               max_bulk_capacity_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_bulk_capacity_volume: "200",
//               max_bulk_capacity_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               max_volume: "300",
//               max_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               restricted_weight_piece: "200",
//               restricted_weight_piece_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_dimension_length: "2",
//               max_dimension_breadth: "1.5",
//               max_dimension_height: "1.5",
//               max_dimension_unit_id: DEFAULT_DIMENSION_UNIT_ID,
//               aft_h: "5",
//               aft_w: "4",
//               fwd_h: "5",
//               fwd_w: "4",
//               bulk_h: "4",
//               bulk_w: "3",
//               bulk_unit_id: DEFAULT_DIMENSION_UNIT_ID,
//               fwt: "15",
//               fwd: "20",
//               bulk: "30",
//               bulk_cubic_id: DEFAULT_VOLUME_UNIT_ID,
//             },
//           },
//         ],
//       },
//       {
//         type: "747",
//         versions: [
//           {
//             version: "400",
//             details: {
//               mtow: "80000",
//               mtow_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_zero_fuel_weight: "58000",
//               max_zero_fuel_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               body_type_id: DEFAULT_BODY_TYPE_ID,
//               passenger_capacity: "140",
//               uld_position: "6",
//               landing_weight: "62000",
//               landing_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               cargo_capacity: "30000",
//               cargo_capacity_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               max_bulk_capacity_weight: "15000",
//               max_bulk_capacity_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_bulk_capacity_volume: "200",
//               max_bulk_capacity_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               max_volume: "300",
//               max_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               restricted_weight_piece: "200",
//               restricted_weight_piece_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_dimension_length: "2",
//               max_dimension_breadth: "1.5",
//               max_dimension_height: "1.5",
//               max_dimension_unit_id: DEFAULT_DIMENSION_UNIT_ID,
//               aft_h: "5",
//               aft_w: "4",
//               fwd_h: "5",
//               fwd_w: "4",
//               bulk_h: "4",
//               bulk_w: "3",
//               bulk_unit_id: DEFAULT_DIMENSION_UNIT_ID,
//               fwt: "15",
//               fwd: "20",
//               bulk: "30",
//               bulk_cubic_id: DEFAULT_VOLUME_UNIT_ID,
//             },
//           },
//           {
//             version: "8",
//             details: {
//               mtow: "80000",
//               mtow_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_zero_fuel_weight: "58000",
//               max_zero_fuel_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               body_type_id: DEFAULT_BODY_TYPE_ID,
//               passenger_capacity: "140",
//               uld_position: "6",
//               landing_weight: "62000",
//               landing_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               cargo_capacity: "30000",
//               cargo_capacity_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               max_bulk_capacity_weight: "15000",
//               max_bulk_capacity_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_bulk_capacity_volume: "200",
//               max_bulk_capacity_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               max_volume: "300",
//               max_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               restricted_weight_piece: "200",
//               restricted_weight_piece_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_dimension_length: "2",
//               max_dimension_breadth: "1.5",
//               max_dimension_height: "1.5",
//               max_dimension_unit_id: DEFAULT_DIMENSION_UNIT_ID,
//               aft_h: "5",
//               aft_w: "4",
//               fwd_h: "5",
//               fwd_w: "4",
//               bulk_h: "4",
//               bulk_w: "3",
//               bulk_unit_id: DEFAULT_DIMENSION_UNIT_ID,
//               fwt: "15",
//               fwd: "20",
//               bulk: "30",
//               bulk_cubic_id: DEFAULT_VOLUME_UNIT_ID,
//             },
//           },
//         ],
//       },
//       {
//         type: "757",
//         versions: [
//           {
//             version: "200",
//             details: {
//               mtow: "80000",
//               mtow_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_zero_fuel_weight: "58000",
//               max_zero_fuel_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               body_type_id: DEFAULT_BODY_TYPE_ID,
//               passenger_capacity: "140",
//               uld_position: "6",
//               landing_weight: "62000",
//               landing_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               cargo_capacity: "30000",
//               cargo_capacity_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               max_bulk_capacity_weight: "15000",
//               max_bulk_capacity_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_bulk_capacity_volume: "200",
//               max_bulk_capacity_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               max_volume: "300",
//               max_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               restricted_weight_piece: "200",
//               restricted_weight_piece_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_dimension_length: "2",
//               max_dimension_breadth: "1.5",
//               max_dimension_height: "1.5",
//               max_dimension_unit_id: DEFAULT_DIMENSION_UNIT_ID,
//               aft_h: "5",
//               aft_w: "4",
//               fwd_h: "5",
//               fwd_w: "4",
//               bulk_h: "4",
//               bulk_w: "3",
//               bulk_unit_id: DEFAULT_DIMENSION_UNIT_ID,
//               fwt: "15",
//               fwd: "20",
//               bulk: "30",
//               bulk_cubic_id: DEFAULT_VOLUME_UNIT_ID,
//             },
//           },
//           {
//             version: "300",
//             details: {
//               mtow: "80000",
//               mtow_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_zero_fuel_weight: "58000",
//               max_zero_fuel_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               body_type_id: DEFAULT_BODY_TYPE_ID,
//               passenger_capacity: "140",
//               uld_position: "6",
//               landing_weight: "62000",
//               landing_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               cargo_capacity: "30000",
//               cargo_capacity_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               max_bulk_capacity_weight: "15000",
//               max_bulk_capacity_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_bulk_capacity_volume: "200",
//               max_bulk_capacity_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               max_volume: "300",
//               max_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               restricted_weight_piece: "200",
//               restricted_weight_piece_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_dimension_length: "2",
//               max_dimension_breadth: "1.5",
//               max_dimension_height: "1.5",
//               max_dimension_unit_id: DEFAULT_DIMENSION_UNIT_ID,
//               aft_h: "5",
//               aft_w: "4",
//               fwd_h: "5",
//               fwd_w: "4",
//               bulk_h: "4",
//               bulk_w: "3",
//               bulk_unit_id: DEFAULT_DIMENSION_UNIT_ID,
//               fwt: "15",
//               fwd: "20",
//               bulk: "30",
//               bulk_cubic_id: DEFAULT_VOLUME_UNIT_ID,
//             },
//           },
//         ],
//       },
//       {
//         type: "767",
//         versions: [
//           {
//             version: "300ER",
//             details: {
//               mtow: "80000",
//               mtow_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_zero_fuel_weight: "58000",
//               max_zero_fuel_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               body_type_id: DEFAULT_BODY_TYPE_ID,
//               passenger_capacity: "140",
//               uld_position: "6",
//               landing_weight: "62000",
//               landing_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               cargo_capacity: "30000",
//               cargo_capacity_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               max_bulk_capacity_weight: "15000",
//               max_bulk_capacity_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_bulk_capacity_volume: "200",
//               max_bulk_capacity_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               max_volume: "300",
//               max_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               restricted_weight_piece: "200",
//               restricted_weight_piece_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_dimension_length: "2",
//               max_dimension_breadth: "1.5",
//               max_dimension_height: "1.5",
//               max_dimension_unit_id: DEFAULT_DIMENSION_UNIT_ID,
//               aft_h: "5",
//               aft_w: "4",
//               fwd_h: "5",
//               fwd_w: "4",
//               bulk_h: "4",
//               bulk_w: "3",
//               bulk_unit_id: DEFAULT_DIMENSION_UNIT_ID,
//               fwt: "15",
//               fwd: "20",
//               bulk: "30",
//               bulk_cubic_id: DEFAULT_VOLUME_UNIT_ID,
//             },
//           },
//           {
//             version: "400ER",
//             details: {
//               mtow: "80000",
//               mtow_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_zero_fuel_weight: "58000",
//               max_zero_fuel_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               body_type_id: DEFAULT_BODY_TYPE_ID,
//               passenger_capacity: "140",
//               uld_position: "6",
//               landing_weight: "62000",
//               landing_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               cargo_capacity: "30000",
//               cargo_capacity_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               max_bulk_capacity_weight: "15000",
//               max_bulk_capacity_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_bulk_capacity_volume: "200",
//               max_bulk_capacity_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               max_volume: "300",
//               max_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               restricted_weight_piece: "200",
//               restricted_weight_piece_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_dimension_length: "2",
//               max_dimension_breadth: "1.5",
//               max_dimension_height: "1.5",
//               max_dimension_unit_id: DEFAULT_DIMENSION_UNIT_ID,
//               aft_h: "5",
//               aft_w: "4",
//               fwd_h: "5",
//               fwd_w: "4",
//               bulk_h: "4",
//               bulk_w: "3",
//               bulk_unit_id: DEFAULT_DIMENSION_UNIT_ID,
//               fwt: "15",
//               fwd: "20",
//               bulk: "30",
//               bulk_cubic_id: DEFAULT_VOLUME_UNIT_ID,
//             },
//           },
//         ],
//       },
//       {
//         type: "777",
//         versions: [
//           {
//             version: "200",
//             details: {
//               mtow: "80000",
//               mtow_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_zero_fuel_weight: "58000",
//               max_zero_fuel_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               body_type_id: DEFAULT_BODY_TYPE_ID,
//               passenger_capacity: "140",
//               uld_position: "6",
//               landing_weight: "62000",
//               landing_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               cargo_capacity: "30000",
//               cargo_capacity_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               max_bulk_capacity_weight: "15000",
//               max_bulk_capacity_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_bulk_capacity_volume: "200",
//               max_bulk_capacity_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               max_volume: "300",
//               max_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               restricted_weight_piece: "200",
//               restricted_weight_piece_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_dimension_length: "2",
//               max_dimension_breadth: "1.5",
//               max_dimension_height: "1.5",
//               max_dimension_unit_id: DEFAULT_DIMENSION_UNIT_ID,
//               aft_h: "5",
//               aft_w: "4",
//               fwd_h: "5",
//               fwd_w: "4",
//               bulk_h: "4",
//               bulk_w: "3",
//               bulk_unit_id: DEFAULT_DIMENSION_UNIT_ID,
//               fwt: "15",
//               fwd: "20",
//               bulk: "30",
//               bulk_cubic_id: DEFAULT_VOLUME_UNIT_ID,
//             },
//           },
//           {
//             version: "200ER",
//             details: {
//               mtow: "80000",
//               mtow_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_zero_fuel_weight: "58000",
//               max_zero_fuel_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               body_type_id: DEFAULT_BODY_TYPE_ID,
//               passenger_capacity: "140",
//               uld_position: "6",
//               landing_weight: "62000",
//               landing_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               cargo_capacity: "30000",
//               cargo_capacity_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               max_bulk_capacity_weight: "15000",
//               max_bulk_capacity_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_bulk_capacity_volume: "200",
//               max_bulk_capacity_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               max_volume: "300",
//               max_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               restricted_weight_piece: "200",
//               restricted_weight_piece_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_dimension_length: "2",
//               max_dimension_breadth: "1.5",
//               max_dimension_height: "1.5",
//               max_dimension_unit_id: DEFAULT_DIMENSION_UNIT_ID,
//               aft_h: "5",
//               aft_w: "4",
//               fwd_h: "5",
//               fwd_w: "4",
//               bulk_h: "4",
//               bulk_w: "3",
//               bulk_unit_id: DEFAULT_DIMENSION_UNIT_ID,
//               fwt: "15",
//               fwd: "20",
//               bulk: "30",
//               bulk_cubic_id: DEFAULT_VOLUME_UNIT_ID,
//             },
//           },
//           {
//             version: "300ER",
//             details: {
//               mtow: "80000",
//               mtow_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_zero_fuel_weight: "58000",
//               max_zero_fuel_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               body_type_id: DEFAULT_BODY_TYPE_ID,
//               passenger_capacity: "140",
//               uld_position: "6",
//               landing_weight: "62000",
//               landing_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               cargo_capacity: "30000",
//               cargo_capacity_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               max_bulk_capacity_weight: "15000",
//               max_bulk_capacity_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_bulk_capacity_volume: "200",
//               max_bulk_capacity_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               max_volume: "300",
//               max_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               restricted_weight_piece: "200",
//               restricted_weight_piece_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_dimension_length: "2",
//               max_dimension_breadth: "1.5",
//               max_dimension_height: "1.5",
//               max_dimension_unit_id: DEFAULT_DIMENSION_UNIT_ID,
//               aft_h: "5",
//               aft_w: "4",
//               fwd_h: "5",
//               fwd_w: "4",
//               bulk_h: "4",
//               bulk_w: "3",
//               bulk_unit_id: DEFAULT_DIMENSION_UNIT_ID,
//               fwt: "15",
//               fwd: "20",
//               bulk: "30",
//               bulk_cubic_id: DEFAULT_VOLUME_UNIT_ID,
//             },
//           },
//           {
//             version: "777X",
//             details: {
//               mtow: "80000",
//               mtow_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_zero_fuel_weight: "58000",
//               max_zero_fuel_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               body_type_id: DEFAULT_BODY_TYPE_ID,
//               passenger_capacity: "140",
//               uld_position: "6",
//               landing_weight: "62000",
//               landing_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               cargo_capacity: "30000",
//               cargo_capacity_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               max_bulk_capacity_weight: "15000",
//               max_bulk_capacity_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_bulk_capacity_volume: "200",
//               max_bulk_capacity_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               max_volume: "300",
//               max_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               restricted_weight_piece: "200",
//               restricted_weight_piece_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_dimension_length: "2",
//               max_dimension_breadth: "1.5",
//               max_dimension_height: "1.5",
//               max_dimension_unit_id: DEFAULT_DIMENSION_UNIT_ID,
//               aft_h: "5",
//               aft_w: "4",
//               fwd_h: "5",
//               fwd_w: "4",
//               bulk_h: "4",
//               bulk_w: "3",
//               bulk_unit_id: DEFAULT_DIMENSION_UNIT_ID,
//               fwt: "15",
//               fwd: "20",
//               bulk: "30",
//               bulk_cubic_id: DEFAULT_VOLUME_UNIT_ID,
//             },
//           },
//         ],
//       },
//       {
//         type: "787",
//         versions: [
//           {
//             version: "8",
//             details: {
//               mtow: "80000",
//               mtow_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_zero_fuel_weight: "58000",
//               max_zero_fuel_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               body_type_id: DEFAULT_BODY_TYPE_ID,
//               passenger_capacity: "140",
//               uld_position: "6",
//               landing_weight: "62000",
//               landing_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               cargo_capacity: "30000",
//               cargo_capacity_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               max_bulk_capacity_weight: "15000",
//               max_bulk_capacity_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_bulk_capacity_volume: "200",
//               max_bulk_capacity_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               max_volume: "300",
//               max_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               restricted_weight_piece: "200",
//               restricted_weight_piece_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_dimension_length: "2",
//               max_dimension_breadth: "1.5",
//               max_dimension_height: "1.5",
//               max_dimension_unit_id: DEFAULT_DIMENSION_UNIT_ID,
//               aft_h: "5",
//               aft_w: "4",
//               fwd_h: "5",
//               fwd_w: "4",
//               bulk_h: "4",
//               bulk_w: "3",
//               bulk_unit_id: DEFAULT_DIMENSION_UNIT_ID,
//               fwt: "15",
//               fwd: "20",
//               bulk: "30",
//               bulk_cubic_id: DEFAULT_VOLUME_UNIT_ID,
//             },
//           },
//           {
//             version: "9",
//             details: {
//               mtow: "80000",
//               mtow_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_zero_fuel_weight: "58000",
//               max_zero_fuel_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               body_type_id: DEFAULT_BODY_TYPE_ID,
//               passenger_capacity: "140",
//               uld_position: "6",
//               landing_weight: "62000",
//               landing_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               cargo_capacity: "30000",
//               cargo_capacity_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               max_bulk_capacity_weight: "15000",
//               max_bulk_capacity_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_bulk_capacity_volume: "200",
//               max_bulk_capacity_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               max_volume: "300",
//               max_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               restricted_weight_piece: "200",
//               restricted_weight_piece_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_dimension_length: "2",
//               max_dimension_breadth: "1.5",
//               max_dimension_height: "1.5",
//               max_dimension_unit_id: DEFAULT_DIMENSION_UNIT_ID,
//               aft_h: "5",
//               aft_w: "4",
//               fwd_h: "5",
//               fwd_w: "4",
//               bulk_h: "4",
//               bulk_w: "3",
//               bulk_unit_id: DEFAULT_DIMENSION_UNIT_ID,
//               fwt: "15",
//               fwd: "20",
//               bulk: "30",
//               bulk_cubic_id: DEFAULT_VOLUME_UNIT_ID,
//             },
//           },
//           {
//             version: "10",
//             details: {
//               mtow: "80000",
//               mtow_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_zero_fuel_weight: "58000",
//               max_zero_fuel_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               body_type_id: DEFAULT_BODY_TYPE_ID,
//               passenger_capacity: "140",
//               uld_position: "6",
//               landing_weight: "62000",
//               landing_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               cargo_capacity: "30000",
//               cargo_capacity_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               max_bulk_capacity_weight: "15000",
//               max_bulk_capacity_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_bulk_capacity_volume: "200",
//               max_bulk_capacity_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               max_volume: "300",
//               max_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               restricted_weight_piece: "200",
//               restricted_weight_piece_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_dimension_length: "2",
//               max_dimension_breadth: "1.5",
//               max_dimension_height: "1.5",
//               max_dimension_unit_id: DEFAULT_DIMENSION_UNIT_ID,
//               aft_h: "5",
//               aft_w: "4",
//               fwd_h: "5",
//               fwd_w: "4",
//               bulk_h: "4",
//               bulk_w: "3",
//               bulk_unit_id: DEFAULT_DIMENSION_UNIT_ID,
//               fwt: "15",
//               fwd: "20",
//               bulk: "30",
//               bulk_cubic_id: DEFAULT_VOLUME_UNIT_ID,
//             },
//           },
//         ],
//       },
//     ],
//   },
//   {
//     manufacturer: "Airbus",
//     types: [
//       {
//         type: "A220",
//         versions: [
//           {
//             version: "100",
//             details: {
//               mtow: "70000",
//               mtow_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_zero_fuel_weight: "58000",
//               max_zero_fuel_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               body_type_id: DEFAULT_BODY_TYPE_ID,
//               passenger_capacity: "140",
//               uld_position: "6",
//               landing_weight: "62000",
//               landing_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               cargo_capacity: "30000",
//               cargo_capacity_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               max_bulk_capacity_weight: "15000",
//               max_bulk_capacity_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_bulk_capacity_volume: "200",
//               max_bulk_capacity_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               max_volume: "300",
//               max_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               restricted_weight_piece: "200",
//               restricted_weight_piece_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_dimension_length: "2",
//               max_dimension_breadth: "1.5",
//               max_dimension_height: "1.5",
//               max_dimension_unit_id: DEFAULT_DIMENSION_UNIT_ID,
//               aft_h: "5",
//               aft_w: "4",
//               fwd_h: "5",
//               fwd_w: "4",
//               bulk_h: "4",
//               bulk_w: "3",
//               bulk_unit_id: DEFAULT_DIMENSION_UNIT_ID,
//               fwt: "15",
//               fwd: "20",
//               bulk: "30",
//               bulk_cubic_id: DEFAULT_VOLUME_UNIT_ID,
//             },
//           },
//           {
//             version: "300",
//             details: {
//               mtow: "80000",
//               mtow_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_zero_fuel_weight: "58000",
//               max_zero_fuel_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               body_type_id: DEFAULT_BODY_TYPE_ID,
//               passenger_capacity: "140",
//               uld_position: "6",
//               landing_weight: "62000",
//               landing_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               cargo_capacity: "30000",
//               cargo_capacity_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               max_bulk_capacity_weight: "15000",
//               max_bulk_capacity_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_bulk_capacity_volume: "200",
//               max_bulk_capacity_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               max_volume: "300",
//               max_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               restricted_weight_piece: "200",
//               restricted_weight_piece_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_dimension_length: "2",
//               max_dimension_breadth: "1.5",
//               max_dimension_height: "1.5",
//               max_dimension_unit_id: DEFAULT_DIMENSION_UNIT_ID,
//               aft_h: "5",
//               aft_w: "4",
//               fwd_h: "5",
//               fwd_w: "4",
//               bulk_h: "4",
//               bulk_w: "3",
//               bulk_unit_id: DEFAULT_DIMENSION_UNIT_ID,
//               fwt: "15",
//               fwd: "20",
//               bulk: "30",
//               bulk_cubic_id: DEFAULT_VOLUME_UNIT_ID,
//             },
//           },
//         ],
//       },
//       {
//         type: "A320",
//         versions: [
//           {
//             version: "A318",
//             details: {
//               mtow: "80000",
//               mtow_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_zero_fuel_weight: "58000",
//               max_zero_fuel_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               body_type_id: DEFAULT_BODY_TYPE_ID,
//               passenger_capacity: "140",
//               uld_position: "6",
//               landing_weight: "62000",
//               landing_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               cargo_capacity: "30000",
//               cargo_capacity_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               max_bulk_capacity_weight: "15000",
//               max_bulk_capacity_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_bulk_capacity_volume: "200",
//               max_bulk_capacity_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               max_volume: "300",
//               max_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               restricted_weight_piece: "200",
//               restricted_weight_piece_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_dimension_length: "2",
//               max_dimension_breadth: "1.5",
//               max_dimension_height: "1.5",
//               max_dimension_unit_id: DEFAULT_DIMENSION_UNIT_ID,
//               aft_h: "5",
//               aft_w: "4",
//               fwd_h: "5",
//               fwd_w: "4",
//               bulk_h: "4",
//               bulk_w: "3",
//               bulk_unit_id: DEFAULT_DIMENSION_UNIT_ID,
//               fwt: "15",
//               fwd: "20",
//               bulk: "30",
//               bulk_cubic_id: DEFAULT_VOLUME_UNIT_ID,
//             },
//           },
//           {
//             version: "A310",
//             details: {
//               mtow: "80000",
//               mtow_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_zero_fuel_weight: "58000",
//               max_zero_fuel_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               body_type_id: DEFAULT_BODY_TYPE_ID,
//               passenger_capacity: "140",
//               uld_position: "6",
//               landing_weight: "62000",
//               landing_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               cargo_capacity: "30000",
//               cargo_capacity_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               max_bulk_capacity_weight: "15000",
//               max_bulk_capacity_weight_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_bulk_capacity_volume: "200",
//               max_bulk_capacity_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               max_volume: "300",
//               max_volume_unit_id: DEFAULT_VOLUME_UNIT_ID,
//               restricted_weight_piece: "200",
//               restricted_weight_piece_unit_id: DEFAULT_WEIGHT_UNIT_ID,
//               max_dimension_length: "2",
//               max_dimension_breadth: "1.5",
//               max_dimension_height: "1.5",
//               max_dimension_unit_id: DEFAULT_DIMENSION_UNIT_ID,
//               aft_h: "5",
//               aft_w: "4",
//               fwd_h: "5",
//               fwd_w: "4",
//               bulk_h: "4",
//               bulk_w: "3",
//               bulk_unit_id: DEFAULT_DIMENSION_UNIT_ID,
//               fwt: "15",
//               fwd: "20",
//               bulk: "30",
//               bulk_cubic_id: DEFAULT_VOLUME_UNIT_ID,
//             },
//           },
//         ],
//       },
//       //   {
//       //     type: "A330",
//       //     versions: ["A330-200", "A330-300", "A330-900neo"],
//       //   },
//       //   {
//       //     type: "A340",
//       //     versions: ["A340-300", "A340-500", "A340-600"],
//       //   },
//       //   {
//       //     type: "A350",
//       //     versions: ["A350-900", "A350-1000"],
//       //   },
//       //   {
//       //     type: "A380",
//       //     versions: ["A380-800"],
//       //   },
//     ],
//   },
// ] as const

// TODO: EXPORT MOCK DATA

export const AIRCRAFT_TYPES_TEST_DATA = [
  {
    ID: "f3734f28-f008-4cf0-bb9b-0c87b2d63793",
    manufacturer: "Airbus",
    aircraft_type: "A330",
    version: "200",
    mtow: "233000",
    mtow_unit: {
      ID: "a708c7ab-c41a-45c3-a3f2-9ae6cb21f47c",
      Name: "Kilograms",
      Symbol: "K",
    },
    max_zero_fuel_weight: "175000",
    max_zero_fuel_weight_unit: {
      ID: "a708c7ab-c41a-45c3-a3f2-9ae6cb21f47c",
      Name: "Kilograms",
      Symbol: "K",
    },
    body_type: {
      ID: "ac201762-5b55-44ab-85c9-0e8f956b8e00",
      Name: "Wide",
    },
    passenger_capacity: "239",
    uld_position: "26",
    landing_weight: "187000",
    landing_weight_unit: {
      ID: "a708c7ab-c41a-45c3-a3f2-9ae6cb21f47c",
      Name: "Kilograms",
      Symbol: "K",
    },
    cargo_capacity: "33300",
    cargo_capacity_unit: {
      ID: "aefd86d6-6fe7-4fcf-8a42-5ef860542401",
      Name: "Cubic Meters",
      Symbol: "Meters",
    },
    max_bulk_capacity_weight: "13500",
    max_bulk_capacity_weight_unit: {
      ID: "a708c7ab-c41a-45c3-a3f2-9ae6cb21f47c",
      Name: "Kilograms",
      Symbol: "K",
    },
    max_bulk_capacity_volume: "14.8",
    max_bulk_capacity_volume_unit: {
      ID: "aefd86d6-6fe7-4fcf-8a42-5ef860542401",
      Name: "Cubic Meters",
      Symbol: "Meters",
    },
    max_volume: "168",
    max_volume_unit: {
      ID: "aefd86d6-6fe7-4fcf-8a42-5ef860542401",
      Name: "Cubic Meters",
      Symbol: "Meters",
    },
    restricted_weight_piece: "200",
    restricted_weight_piece_unit: {
      ID: "a708c7ab-c41a-45c3-a3f2-9ae6cb21f47c",
      Name: "Kilograms",
      Symbol: "K",
    },
    max_dimension_length: "3",
    max_dimension_breadth: "2.4",
    max_dimension_height: "1.7",
    max_dimension_unit: {
      ID: "767c9495-c8f8-48fe-82cb-28d7a42a016d",
      Name: "Centimeters",
      Symbol: "Cms",
    },
    status: {
      ID: "a2a781e6-c892-46e4-ab3e-fb344727cfd8",
      Name: "Active",
    },
    gl_code: {
      ID: "1161055d-0f85-48f4-844e-0c29add31ba8",
      Name: "Narrow",
    },
    count: 1,
    aircraft_tail_numbers: [
      {
        ID: "143d0df8-4624-4505-9ae8-fbea7af98baa",
        tail_number: "KOM",
        status: {
          ID: "a2a781e6-c892-46e4-ab3e-fb344727cfd8",
          Name: "Active",
        },
      },
    ],
    aft_h: "1.65",
    aft_w: "3.58",
    fwd_h: "1.65",
    fwd_w: "3.58",
    bulk_h: "1.12",
    bulk_w: "1.35",
    bulk_unit: {
      ID: "767c9495-c8f8-48fe-82cb-28d7a42a016d",
      Name: "Centimeters",
      Symbol: "Cms",
    },
    fwt: "15",
    fwd: "20",
    bulk: "30",
    bulk_cubic: {
      ID: "aefd86d6-6fe7-4fcf-8a42-5ef860542401",
      Name: "Cubic Meters",
      Symbol: "Meters",
    },
    created_at: "2024-06-28T06:20:02.841907Z",
    updated_at: "2024-07-08T15:16:23.649526Z",
    deleted_at: null,
  },
  {
    ID: "0f9a8b48-94d5-4b41-9de8-b7766b66754c",
    manufacturer: "Airbus",
    aircraft_type: "A330",
    version: "200",
    mtow: "233000",
    mtow_unit: {
      ID: "a708c7ab-c41a-45c3-a3f2-9ae6cb21f47c",
      Name: "Kilograms",
      Symbol: "K",
    },
    max_zero_fuel_weight: "175000",
    max_zero_fuel_weight_unit: {
      ID: "a708c7ab-c41a-45c3-a3f2-9ae6cb21f47c",
      Name: "Kilograms",
      Symbol: "K",
    },
    body_type: {
      ID: "ac201762-5b55-44ab-85c9-0e8f956b8e00",
      Name: "Wide",
    },
    passenger_capacity: "239",
    uld_position: "26",
    landing_weight: "187000",
    landing_weight_unit: {
      ID: "a708c7ab-c41a-45c3-a3f2-9ae6cb21f47c",
      Name: "Kilograms",
      Symbol: "K",
    },
    cargo_capacity: "33300",
    cargo_capacity_unit: {
      ID: "aefd86d6-6fe7-4fcf-8a42-5ef860542401",
      Name: "Cubic Meters",
      Symbol: "Meters",
    },
    max_bulk_capacity_weight: "13500",
    max_bulk_capacity_weight_unit: {
      ID: "a708c7ab-c41a-45c3-a3f2-9ae6cb21f47c",
      Name: "Kilograms",
      Symbol: "K",
    },
    max_bulk_capacity_volume: "14.8",
    max_bulk_capacity_volume_unit: {
      ID: "aefd86d6-6fe7-4fcf-8a42-5ef860542401",
      Name: "Cubic Meters",
      Symbol: "Meters",
    },
    max_volume: "168",
    max_volume_unit: {
      ID: "aefd86d6-6fe7-4fcf-8a42-5ef860542401",
      Name: "Cubic Meters",
      Symbol: "Meters",
    },
    restricted_weight_piece: "200",
    restricted_weight_piece_unit: {
      ID: "a708c7ab-c41a-45c3-a3f2-9ae6cb21f47c",
      Name: "Kilograms",
      Symbol: "K",
    },
    max_dimension_length: "3",
    max_dimension_breadth: "2.4",
    max_dimension_height: "1.7",
    max_dimension_unit: {
      ID: "767c9495-c8f8-48fe-82cb-28d7a42a016d",
      Name: "Centimeters",
      Symbol: "Cms",
    },
    status: {
      ID: "a2a781e6-c892-46e4-ab3e-fb344727cfd8",
      Name: "Active",
    },
    gl_code: {
      ID: "1161055d-0f85-48f4-844e-0c29add31ba8",
      Name: "Narrow",
    },
    count: 1,
    aircraft_tail_numbers: [
      {
        ID: "515aff7a-d34e-4a93-92a9-d79a2fbf4d91",
        tail_number: "NUL",
        status: {
          ID: "a2a781e6-c892-46e4-ab3e-fb344727cfd8",
          Name: "Active",
        },
      },
    ],
    aft_h: "1.65",
    aft_w: "3.58",
    fwd_h: "1.65",
    fwd_w: "3.58",
    bulk_h: "1.12",
    bulk_w: "1.35",
    bulk_unit: {
      ID: "767c9495-c8f8-48fe-82cb-28d7a42a016d",
      Name: "Centimeters",
      Symbol: "Cms",
    },
    fwt: "15",
    fwd: "20",
    bulk: "30",
    bulk_cubic: {
      ID: "aefd86d6-6fe7-4fcf-8a42-5ef860542401",
      Name: "Cubic Meters",
      Symbol: "Meters",
    },
    created_at: "2024-06-28T06:19:50.173779Z",
    updated_at: "2024-07-09T08:25:30.141931Z",
    deleted_at: null,
  },
  {
    ID: "e89606d8-c8e8-4424-858a-665c1970e177",
    manufacturer: "Airbus",
    aircraft_type: "A330",
    version: "200",
    mtow: "233000",
    mtow_unit: {
      ID: "a708c7ab-c41a-45c3-a3f2-9ae6cb21f47c",
      Name: "Kilograms",
      Symbol: "K",
    },
    max_zero_fuel_weight: "175000",
    max_zero_fuel_weight_unit: {
      ID: "a708c7ab-c41a-45c3-a3f2-9ae6cb21f47c",
      Name: "Kilograms",
      Symbol: "K",
    },
    body_type: {
      ID: "ac201762-5b55-44ab-85c9-0e8f956b8e00",
      Name: "Wide",
    },
    passenger_capacity: "239",
    uld_position: "26",
    landing_weight: "187000",
    landing_weight_unit: {
      ID: "a708c7ab-c41a-45c3-a3f2-9ae6cb21f47c",
      Name: "Kilograms",
      Symbol: "K",
    },
    cargo_capacity: "33300",
    cargo_capacity_unit: {
      ID: "aefd86d6-6fe7-4fcf-8a42-5ef860542401",
      Name: "Cubic Meters",
      Symbol: "Meters",
    },
    max_bulk_capacity_weight: "13500",
    max_bulk_capacity_weight_unit: {
      ID: "a708c7ab-c41a-45c3-a3f2-9ae6cb21f47c",
      Name: "Kilograms",
      Symbol: "K",
    },
    max_bulk_capacity_volume: "14.8",
    max_bulk_capacity_volume_unit: {
      ID: "aefd86d6-6fe7-4fcf-8a42-5ef860542401",
      Name: "Cubic Meters",
      Symbol: "Meters",
    },
    max_volume: "168",
    max_volume_unit: {
      ID: "aefd86d6-6fe7-4fcf-8a42-5ef860542401",
      Name: "Cubic Meters",
      Symbol: "Meters",
    },
    restricted_weight_piece: "200",
    restricted_weight_piece_unit: {
      ID: "a708c7ab-c41a-45c3-a3f2-9ae6cb21f47c",
      Name: "Kilograms",
      Symbol: "K",
    },
    max_dimension_length: "3",
    max_dimension_breadth: "2.4",
    max_dimension_height: "1.7",
    max_dimension_unit: {
      ID: "767c9495-c8f8-48fe-82cb-28d7a42a016d",
      Name: "Centimeters",
      Symbol: "Cms",
    },
    status: {
      ID: "a2a781e6-c892-46e4-ab3e-fb344727cfd8",
      Name: "Active",
    },
    gl_code: {
      ID: "1161055d-0f85-48f4-844e-0c29add31ba8",
      Name: "Narrow",
    },
    count: 1,
    aircraft_tail_numbers: [
      {
        ID: "02301892-2bf4-47b5-b1ec-957246fdfe95",
        tail_number: "JQG",
        status: {
          ID: "a2a781e6-c892-46e4-ab3e-fb344727cfd8",
          Name: "Active",
        },
      },
    ],
    aft_h: "1.65",
    aft_w: "3.58",
    fwd_h: "1.65",
    fwd_w: "3.58",
    bulk_h: "1.12",
    bulk_w: "1.35",
    bulk_unit: {
      ID: "767c9495-c8f8-48fe-82cb-28d7a42a016d",
      Name: "Centimeters",
      Symbol: "Cms",
    },
    fwt: "15",
    fwd: "20",
    bulk: "30",
    bulk_cubic: {
      ID: "aefd86d6-6fe7-4fcf-8a42-5ef860542401",
      Name: "Cubic Meters",
      Symbol: "Meters",
    },
    created_at: "2024-06-28T06:19:09.749942Z",
    updated_at: "2024-07-05T02:55:53.181098Z",
    deleted_at: null,
  },
  {
    ID: "77473c00-3e2c-494d-a2ab-b2b993d90ef8",
    manufacturer: "Airbus",
    aircraft_type: "A330",
    version: "200",
    mtow: "233000",
    mtow_unit: {
      ID: "a708c7ab-c41a-45c3-a3f2-9ae6cb21f47c",
      Name: "Kilograms",
      Symbol: "K",
    },
    max_zero_fuel_weight: "175000",
    max_zero_fuel_weight_unit: {
      ID: "a708c7ab-c41a-45c3-a3f2-9ae6cb21f47c",
      Name: "Kilograms",
      Symbol: "K",
    },
    body_type: {
      ID: "ac201762-5b55-44ab-85c9-0e8f956b8e00",
      Name: "Wide",
    },
    passenger_capacity: "239",
    uld_position: "26",
    landing_weight: "187000",
    landing_weight_unit: {
      ID: "a708c7ab-c41a-45c3-a3f2-9ae6cb21f47c",
      Name: "Kilograms",
      Symbol: "K",
    },
    cargo_capacity: "33300",
    cargo_capacity_unit: {
      ID: "aefd86d6-6fe7-4fcf-8a42-5ef860542401",
      Name: "Cubic Meters",
      Symbol: "Meters",
    },
    max_bulk_capacity_weight: "13500",
    max_bulk_capacity_weight_unit: {
      ID: "a708c7ab-c41a-45c3-a3f2-9ae6cb21f47c",
      Name: "Kilograms",
      Symbol: "K",
    },
    max_bulk_capacity_volume: "14.8",
    max_bulk_capacity_volume_unit: {
      ID: "aefd86d6-6fe7-4fcf-8a42-5ef860542401",
      Name: "Cubic Meters",
      Symbol: "Meters",
    },
    max_volume: "168",
    max_volume_unit: {
      ID: "aefd86d6-6fe7-4fcf-8a42-5ef860542401",
      Name: "Cubic Meters",
      Symbol: "Meters",
    },
    restricted_weight_piece: "200",
    restricted_weight_piece_unit: {
      ID: "a708c7ab-c41a-45c3-a3f2-9ae6cb21f47c",
      Name: "Kilograms",
      Symbol: "K",
    },
    max_dimension_length: "3",
    max_dimension_breadth: "2.4",
    max_dimension_height: "1.7",
    max_dimension_unit: {
      ID: "767c9495-c8f8-48fe-82cb-28d7a42a016d",
      Name: "Centimeters",
      Symbol: "Cms",
    },
    status: {
      ID: "a2a781e6-c892-46e4-ab3e-fb344727cfd8",
      Name: "Active",
    },
    gl_code: {
      ID: "1161055d-0f85-48f4-844e-0c29add31ba8",
      Name: "Narrow",
    },
    count: 1,
    aircraft_tail_numbers: [
      {
        ID: "063cb8c4-06ac-4559-aa34-4f9e00f7d56e",
        tail_number: "OAQ",
        status: {
          ID: "a2a781e6-c892-46e4-ab3e-fb344727cfd8",
          Name: "Active",
        },
      },
    ],
    aft_h: "1.65",
    aft_w: "3.58",
    fwd_h: "1.65",
    fwd_w: "3.58",
    bulk_h: "1.12",
    bulk_w: "1.35",
    bulk_unit: {
      ID: "767c9495-c8f8-48fe-82cb-28d7a42a016d",
      Name: "Centimeters",
      Symbol: "Cms",
    },
    fwt: "15",
    fwd: "20",
    bulk: "30",
    bulk_cubic: {
      ID: "aefd86d6-6fe7-4fcf-8a42-5ef860542401",
      Name: "Cubic Meters",
      Symbol: "Meters",
    },
    created_at: "2024-06-19T13:38:29.014176Z",
    updated_at: "2024-07-08T13:42:39.46593Z",
    deleted_at: null,
  },
  {
    ID: "c36f2550-c12e-4276-824b-73b88f7b9e17",
    manufacturer: "Airbus",
    aircraft_type: "A330",
    version: "200",
    mtow: "233000",
    mtow_unit: {
      ID: "a708c7ab-c41a-45c3-a3f2-9ae6cb21f47c",
      Name: "Kilograms",
      Symbol: "K",
    },
    max_zero_fuel_weight: "175000",
    max_zero_fuel_weight_unit: {
      ID: "a708c7ab-c41a-45c3-a3f2-9ae6cb21f47c",
      Name: "Kilograms",
      Symbol: "K",
    },
    body_type: {
      ID: "ac201762-5b55-44ab-85c9-0e8f956b8e00",
      Name: "Wide",
    },
    passenger_capacity: "239",
    uld_position: "26",
    landing_weight: "187000",
    landing_weight_unit: {
      ID: "a708c7ab-c41a-45c3-a3f2-9ae6cb21f47c",
      Name: "Kilograms",
      Symbol: "K",
    },
    cargo_capacity: "33300",
    cargo_capacity_unit: {
      ID: "aefd86d6-6fe7-4fcf-8a42-5ef860542401",
      Name: "Cubic Meters",
      Symbol: "Meters",
    },
    max_bulk_capacity_weight: "13500",
    max_bulk_capacity_weight_unit: {
      ID: "a708c7ab-c41a-45c3-a3f2-9ae6cb21f47c",
      Name: "Kilograms",
      Symbol: "K",
    },
    max_bulk_capacity_volume: "14.8",
    max_bulk_capacity_volume_unit: {
      ID: "aefd86d6-6fe7-4fcf-8a42-5ef860542401",
      Name: "Cubic Meters",
      Symbol: "Meters",
    },
    max_volume: "168",
    max_volume_unit: {
      ID: "aefd86d6-6fe7-4fcf-8a42-5ef860542401",
      Name: "Cubic Meters",
      Symbol: "Meters",
    },
    restricted_weight_piece: "200",
    restricted_weight_piece_unit: {
      ID: "a708c7ab-c41a-45c3-a3f2-9ae6cb21f47c",
      Name: "Kilograms",
      Symbol: "K",
    },
    max_dimension_length: "3",
    max_dimension_breadth: "2.4",
    max_dimension_height: "1.7",
    max_dimension_unit: {
      ID: "767c9495-c8f8-48fe-82cb-28d7a42a016d",
      Name: "Centimeters",
      Symbol: "Cms",
    },
    status: {
      ID: "a2a781e6-c892-46e4-ab3e-fb344727cfd8",
      Name: "Active",
    },
    gl_code: {
      ID: "1161055d-0f85-48f4-844e-0c29add31ba8",
      Name: "Narrow",
    },
    count: 1,
    aircraft_tail_numbers: [
      {
        ID: "f90f0cf6-79c3-4503-b8ee-88c5980ea15d",
        tail_number: "OAP",
        status: {
          ID: "a2a781e6-c892-46e4-ab3e-fb344727cfd8",
          Name: "Active",
        },
      },
    ],
    aft_h: "1.65",
    aft_w: "3.58",
    fwd_h: "1.65",
    fwd_w: "3.58",
    bulk_h: "1.12",
    bulk_w: "1.35",
    bulk_unit: {
      ID: "767c9495-c8f8-48fe-82cb-28d7a42a016d",
      Name: "Centimeters",
      Symbol: "Cms",
    },
    fwt: "15",
    fwd: "20",
    bulk: "30",
    bulk_cubic: {
      ID: "aefd86d6-6fe7-4fcf-8a42-5ef860542401",
      Name: "Cubic Meters",
      Symbol: "Meters",
    },
    created_at: "2024-07-08T03:18:24.07393Z",
    updated_at: "2024-07-08T03:18:24.07393Z",
    deleted_at: null,
  },
]
