import { AircraftFormValues } from "@/schemas/aircraft/aircraft"

export const formDefaultValues: AircraftFormValues = {
  aft_h: "",
  aft_w: "",
  aircraft_tail_numbers: [
    {
      id: "",
      status_id: "",
      tail_number: "",
    },
  ],
  aircraft_type_id: "",
  body_type_id: "",
  bulk: "",
  bulk_h: "",
  bulk_w: "",
  cargo_capacity: "",
  fwd: "",
  fwd_h: "",
  fwd_w: "",
  count: 0,
  fwt: "",
  gl_code_id: "",
  landing_weight: "",
  max_bulk_capacity_volume: "",
  max_bulk_capacity_weight: "",
  max_dimension_breadth: "",
  max_dimension_height: "",
  manufacturer_id: "",
  max_dimension_length: "",
  max_volume: "",
  max_zero_fuel_weight: "",
  mtow: "",
  passenger_capacity: "",
  restricted_weight_piece: "",
  status_id: "",
  uld_position: "",
  version_id: "",
  dimension_unit_id: "",
  volume_unit_id: "",
  weight_unit_id: "",
}
