import { z } from "zod"

export const orderSchema = z.object({
  ID: z.string().optional(),
  amount_due: z.string().optional(),
  activity_logs: z
    .array(
      z
        .object({
          ID: z.string(),
          created_at: z.string(),
          updated_at: z.string(),
          user: z
            .object({
              ID: z.string(),
              name: z.string(),
              email: z.string().email(),
            })
            .optional(),
          action: z.string(),
        })
        .optional()
    )
    .optional()
    .nullable(),
  awb: z.string().optional(),
  bill_to_id: z.string().optional(),
  bill_to_old_name: z.string().optional().nullable(),
  bill_to_name: z.string().optional().nullable(),
  booking_type_id: z.string().min(1, { message: "Please select Booking Type" }).optional(),
  ch_weight_kg: z.string().optional(),
  commodity_code_id: z.string().optional(),
  consignee_id: z.string().optional(),
  currency_id: z.string().optional(),
  customer_id: z.string().optional(),
  destination_id: z.string().optional(),
  freight_forwarder_id: z.string().optional(),
  gs_weight_kg: z.string().optional(),
  is_physical: z.string().optional(),
  mode: z.string().optional(),
  organization_id: z.string().optional(),
  origin_id: z.string().optional(),
  partner_code_id: z.string().optional(),
  partner_prefix_id: z.string().optional(),
  shipper_details: z
    .array(
      z.object({
        ID: z.string().optional(),
        transport_method_id: z.string().optional(),
        origin_id: z.string().optional(),
        destination_id: z.string().optional(),
        partner_type_id: z.string().optional(),
        partner_code_id: z.string().optional(),
        date: z.union([z.date(), z.string()]),
        flight_code: z.string().optional(),
        allotment_code: z.string().optional(),
        status_id: z.string().optional(),
      })
    ),
  // shipper_details: z.any(),
  payment_mode_id: z.string().optional(),
  rate: z.string().optional(),
  s_freight: z.string().optional(),
  s_rate: z.string().optional(),
  shipper_id: z.string().optional(),
  spot_id: z.string().optional(),
  status_id: z.string().optional(),
  total: z.string().optional(),
  volume_kg: z.string().optional(),
  use_freight_forwarder: z.string().optional(),
  weight_and_volume_type: z.string().optional(),
  hawb_form: z.object({
    booking_type_id: z.string().optional(),
    partner_prefix_id: z.string().optional(),
    awb: z.string().optional(),
    partner_code_id: z.string().optional(),
    origin_id: z.string().optional(),
    destination_id: z.string().optional(),
    consignor_id: z.string().optional(),
    consignee_id: z.string().optional(),
    weight: z.string().optional(),
    weight_unit: z.string().optional(),
    volume: z.string().optional(),
    volume_unit: z.string().optional(),
  }),
  individual_parcel_form: z.object({
    description: z.string().optional(),
    internal_id: z.string().optional(),
    external_id: z.string().optional(),
    weight: z.string().optional(),
    weight_unit: z.string().optional(),
    volume: z.string().optional(),
    volume_unit: z.string().optional(),
    summary_weight: z.string().optional(),
    summary_length: z.string().optional(),
    summary_height: z.string().optional(),
    commodity_code_id: z.string().optional(),
  }),
  total_weight_volume_form: z.object({
    description: z.string().optional(),
    internal_id: z.string().optional(),
    external_id: z.string().optional(),
    weight: z.string().optional(),
    weight_unit: z.string().optional(),
    volume: z.string().optional(),
    volume_unit: z.string().optional(),
    summary_weight: z.string().optional(),
    summary_length: z.string().optional(),
    summary_height: z.string().optional(),
    commodity_code_id: z.string().optional(),
  }),
  hawb_table: z.array(
    z.object({
      id: z.string().optional(),
      booking_type: z.string().optional(),
      booking_type_id: z.string().optional(),
      awb: z.string().optional(),
      origin: z.string().optional(),
      origin_id: z.string().optional(),
      destination: z.string().optional(),
      destination_id: z.string().optional(),
      consignor: z.string().optional(),
      consignor_id: z.string().optional(),
      consignee: z.string().optional(),
      weight: z.string().optional(),
      weight_unit: z.string().optional(),
      volume: z.string().optional(),
      volume_unit: z.string().optional(),
    }).optional(),
  ).optional(),
  individual_parcel_table: z.array(
    z.object({
      id: z.string().optional(),
      description: z.string().optional(),
      internal_id: z.string().optional(),
      external_id: z.string().optional(),
      weight: z.string().optional(),
      weight_unit: z.string().optional(),
      volume: z.string().optional(),
      volume_unit: z.string().optional(),
      summary_weight: z.string().optional(),
      summary_length: z.string().optional(),
      summary_height: z.string().optional(),
      commodity_code_id: z.string().optional(),
      commodity_code: z.string().optional(),
    }).optional(),
  ).optional(),
  total_weight: z.string().optional(),
  total_volume: z.string().optional(),
})

export type Order = z.infer<typeof orderSchema>
