export const dummyData = [
  {
    serialNumber: 1,
    filename: "data_upload_01.csv",
    uploadedBy: "Alice",
    station: "JFK",
    recordCount: 150,
    successCount: 140,
    failureCount: 10,
    updatedAt: "2024-06-01 08:00",
    action: "Reviewed",
  },
  {
    serialNumber: 2,
    filename: "data_upload_02.csv",
    uploadedBy: "Bob",
    station: "LAX",
    recordCount: 200,
    successCount: 190,
    failureCount: 10,
    updatedAt: "2024-06-02 09:00",
    action: "Pending",
  },
  {
    serialNumber: 3,
    filename: "data_upload_03.csv",
    uploadedBy: "Charlie",
    station: "ORD",
    recordCount: 180,
    successCount: 170,
    failureCount: 10,
    updatedAt: "2024-06-03 10:00",
    action: "Approved",
  },
  {
    serialNumber: 4,
    filename: "data_upload_04.csv",
    uploadedBy: "David",
    station: "DFW",
    recordCount: 160,
    successCount: 150,
    failureCount: 10,
    updatedAt: "2024-06-04 11:00",
    action: "Reviewed",
  },
  {
    serialNumber: 5,
    filename: "data_upload_05.csv",
    uploadedBy: "Eva",
    station: "ATL",
    recordCount: 170,
    successCount: 160,
    failureCount: 10,
    updatedAt: "2024-06-05 12:00",
    action: "Pending",
  },
]
