export const warehouses = [
  { key: "WH001", value: "Warehouse A" },
  { key: "WH002", value: "Warehouse B" },
  { key: "WH003", value: "Warehouse C" },
  { key: "WH004", value: "Warehouse D" },
  { key: "WH005", value: "Warehouse E" },
  { key: "WH006", value: "Warehouse F" },
  { key: "WH007", value: "Warehouse G" },
  { key: "WH008", value: "Warehouse H" },
  { key: "WH009", value: "Warehouse I" },
  { key: "WH010", value: "Warehouse J" },
]

export const dummyData = [
  {
    profilePic: "profile_pic_001.jpg",
    userEmail: "user1@example.com",
    role: "Administrator",
    station: "JFK",
    browser: "Chrome",
    os: "Windows 10",
    device: "Desktop",
    activityTime: "2024-05-01T10:00:00Z",
    ipAddress: "192.168.1.1",
    country: "USA",
    city: "New York",
    region: "New York",
  },
  {
    profilePic: "profile_pic_002.jpg",
    userEmail: "user2@example.com",
    role: "User",
    station: "LAX",
    browser: "Firefox",
    os: "macOS",
    device: "Laptop",
    activityTime: "2024-05-02T11:00:00Z",
    ipAddress: "192.168.1.2",
    country: "USA",
    city: "Los Angeles",
    region: "California",
  },
  {
    profilePic: "profile_pic_003.jpg",
    userEmail: "user3@example.com",
    role: "Moderator",
    station: "ORD",
    browser: "Safari",
    os: "iOS",
    device: "iPhone",
    activityTime: "2024-05-03T12:00:00Z",
    ipAddress: "192.168.1.3",
    country: "USA",
    city: "Chicago",
    region: "Illinois",
  },
  {
    profilePic: "profile_pic_004.jpg",
    userEmail: "user4@example.com",
    role: "User",
    station: "ATL",
    browser: "Edge",
    os: "Windows 11",
    device: "Desktop",
    activityTime: "2024-05-04T13:00:00Z",
    ipAddress: "192.168.1.4",
    country: "USA",
    city: "Atlanta",
    region: "Georgia",
  },
  {
    profilePic: "profile_pic_005.jpg",
    userEmail: "user5@example.com",
    role: "Administrator",
    station: "SFO",
    browser: "Chrome",
    os: "Linux",
    device: "Laptop",
    activityTime: "2024-05-05T14:00:00Z",
    ipAddress: "192.168.1.5",
    country: "USA",
    city: "San Francisco",
    region: "California",
  },
]
