import { AwbType, UldType } from "@/components/operation/Delivery/DeliveryCargo/columns";

export const DUMMY_DATA_AWB: AwbType[] = [
  {
    do_number: "001",
    collect: "Yes",
    consignee: "Company A",
    awb_number: "AWB001",
    hawb_number: "HAWB001",
    custom_check: "Cleared",
    custom_code: "C001",
    origin: "NYC",
    destination: "LON",
    arr_pcs: "100",
    arr_wt: "1000kg",
    uom: "kg",
    dlr_pcs: "90",
    dlr_wt: "900kg",
    dlrd_pcs: "10",
    dlrd_wt: "100kg",
    rem_pcs: "0",
    flt_number: "FL123",
    flt_date: "2024-06-01",
    comm_desc: "Electronics",
    agent: "Agent X",
    accepted_pcs: "90",
    payment_type: "Prepaid",
    invoice: "INV001",
    charges: "1000",
    tax: "200",
    total: "1200",
    amt_due: "0",
    updated_on: "2024-06-02"
  },
  {
    do_number: "002",
    collect: "No",
    consignee: "Company B",
    awb_number: "AWB002",
    hawb_number: "HAWB002",
    custom_check: "Pending",
    custom_code: "C002",
    origin: "LAX",
    destination: "SYD",
    arr_pcs: "50",
    arr_wt: "500kg",
    uom: "kg",
    dlr_pcs: "45",
    dlr_wt: "450kg",
    dlrd_pcs: "5",
    dlrd_wt: "50kg",
    rem_pcs: "0",
    flt_number: "FL456",
    flt_date: "2024-06-03",
    comm_desc: "Clothing",
    agent: "Agent Y",
    accepted_pcs: "45",
    payment_type: "Collect",
    invoice: "INV002",
    charges: "500",
    tax: "100",
    total: "600",
    amt_due: "600",
    updated_on: "2024-06-04"
  }
];

export const DUMMY_DATA_ULD: UldType[] = [
  {
    do_number: "003",
    collect: "Yes",
    consignee: "Company C",
    uld: "ULD003",
    awb: "AWB003",
    awb_ct: "AWB_CT003",
    custom_check: "Cleared",
    custom_code: "C003",
    origin: "CHI",
    destination: "TOR",
    arr_pcs: "70",
    arr_wt: "700kg",
    uom: "kg",
    dlr_pcs: "65",
    dlr_wt: "650kg",
    dlrd_pcs: "5",
    rem_pcs: "0",
    rem_wt: "0kg",
    dlrd_wt: "50kg",
    flt_number: "FL789",
    flt_date: "2024-06-05",
    comm_desc: "Furniture",
    agent: "Agent Z",
    accepted_pcs: "65",
    payment_type: "Prepaid",
    invoice: "INV003",
    charges: "700",
    tax: "140",
    total: "840",
    amt_due: "0",
    updated_on: "2024-06-06"
  },
  {
    do_number: "004",
    collect: "No",
    consignee: "Company D",
    uld: "ULD004",
    awb: "AWB004",
    awb_ct: "AWB_CT004",
    custom_check: "Pending",
    custom_code: "C004",
    origin: "MIA",
    destination: "JFK",
    arr_pcs: "30",
    arr_wt: "300kg",
    uom: "kg",
    dlr_pcs: "28",
    dlr_wt: "280kg",
    dlrd_pcs: "2",
    rem_pcs: "0",
    rem_wt: "0kg",
    dlrd_wt: "20kg",
    flt_number: "FL012",
    flt_date: "2024-06-07",
    comm_desc: "Toys",
    agent: "Agent W",
    accepted_pcs: "28",
    payment_type: "Collect",
    invoice: "INV004",
    charges: "300",
    tax: "60",
    total: "360",
    amt_due: "360",
    updated_on: "2024-06-08"
  }
];

export async function getDataAwb() {
  return DUMMY_DATA_AWB;
}

export async function getDataUld() {
  return DUMMY_DATA_ULD;
}
